### ISSUE TITLE
报错 

### ISSUE THREAD

**Issue by ttmouse** [xhnbzdl/feishu-doc-export#12]
Unhandled exception. System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus , TypeCode )
   at System.Number.ParseInt32(ReadOnlySpan`1 , NumberStyles , NumberFormatInfo )
   at System.Int32.Parse(String s)
   at feishu_doc_export.Program.Main(String[] args)
   at feishu_doc_export.Program.<Main>(String[] args)
zsh: abort      sudo ./feishu-doc-export --appId=cli_a5881ee8983a100e

**Comment by xhnbzdl** [comment]
请问你使用的是哪个版本的

**Comment by ttmouse** [comment]
最新的 0.3

跑一半之后提示这个   然后重新输入指令  重新让我输入密码 。

我这个时候会去知识库中调整知识库内文档结构的顺序，把没跑的移动到前面。

这样连续好几次  也可以勉强跑完。

**Comment by xhnbzdl** [comment]
方便加个qq让我看看是如何操作的吗，我看看能否修复一下

**Comment by ttmouse** [comment]
67978478
你的qq设置了不能搜索添加

**Comment by xhnbzdl** [comment]
1.超时重试
2.优化异常处理
3.多维表格

**Comment by xhnbzdl** [comment]
已修复，最新版本：[0.0.4](https://github.com/xhnbzdl/feishu-doc-export/releases/tag/0.0.4)
