### ISSUE TITLE
Build project，run command throw error

### ISSUE THREAD

**Issue by liumingmin** [xhnbzdl/feishu-doc-export#30]
vs2022
.net6.0
Build project，run command throw error:

Unhandled exception. System.NotSupportedException: The invoked member is not supported in a dynamic assembly.
   at System.Reflection.Emit.InternalAssemblyBuilder.GetManifestResourceNames()
   at ???(Object )
   at ?.??(Object )
   at ?.??(MethodBase , Boolean )
   at ?.?(? , ? )
   at ?.?()
   at ?.??(Boolean )
   at ???(Object )
   at ?.??(Object )
   at ?()
   at ?.??(Object , UInt32 )
   at ?.??(Boolean )
   at ???(Object[] , Type[] , Type[] , Object[])
   at ?.??(Int32 , Type[] , Type[] , Boolean)
   at ?.??(? , ? )
   at ?.?()
   at ?.??(Boolean )
   at ???(Object )
   at ?.??(Object )
   at ??()
   at ?.??(Object , UInt32 )
   at ?.??(Boolean )
   at ???(Object[] , Type[] , Type[] , Object[])
   at ?.??(Stream , String , Object[] , Type[], Type[] , Object[] )
   at Aspose.Words.License.SetLicense(String licenseName)
   at feishu_doc_export.GlobalConfig.InitAsposeLicense() in D:\feishu-doc-export\src\feishu-doc-export\GlobalConfig.cs:line 61
   at feishu_doc_export.GlobalConfig.Init(String[] args) in D:\feishu-doc-export\src\feishu-doc-export\GlobalConfig.cs:line 126
   at feishu_doc_export.Program.Main(String[] args) in D:\feishu-doc-export\src\feishu-doc-export\Program.cs:line 21
   at feishu_doc_export.Program.<Main>(String[] args)

**Comment by xhnbzdl** [comment]
这里是用到了一个不免费开源的库，所以license文件我没上传到仓库

**Comment by izhangxiaopeng** [comment]
Comments these code which load license just work.
